### ISSUE TITLE
ff2img - python 3 does not work, python 2 creates unusable image ?

### ISSUE THREAD

**Issue by GrahamBriggs** [t0x0/random#5] opened 2015-06-23 03:55 UTC
Tried ff2img.py, ran successfully.  Put image file on RPi and it booted to windows screen then went blank.

Tried ff2img.py3, got this error:

GBMacBookPro:diskFormat grahambriggs$ python ffu2img.py3 /Users/grahambriggs/Downloads/Windows_IoT_Core_RPI2_BUILD/Flash.ffu RPiWindows3.img
  File "ffu2img.py3", line 94
    print((str(iBlock) + ' blocks, ' + str((iBlock*FFUStoreHeader.dwBlockSizeInBytes)/1024) + 'kb written                                '), end='\r')
                                                                                                                                                ^

Thank you

**Comment by t0x0** [comment] 2015-06-23 05:35
Are you using the May 12 release of the FFU?

Please reply with the SHA256 hash of the FFU file and the img file converted with Py2.7 (the one that does not work on your Raspberry Pi 2).

What is the output from the script with Py2.7?

What is the full error message with Py3? (you cut off the last line of the error message)

**Comment by GrahamBriggs** [comment] 2015-06-24 22:37
Sorry for the delay responding. 

I will look at this again tonight and get back to you with answers to your questions. 

GB
=-=-=-=-=-=-=
Graham Briggs

**Comment by t0x0** [comment] 2015-06-30 08:59
Any results?

**Comment by t0x0** [comment] 2015-07-09 05:23
I will be closing this issue unless you have anything further to report.

**Closed as completed** 2015-07-13 21:24 UTC

**Comment by slandsaw** [comment] 2015-12-29 23:14
Sorry for the comment on an old post. I worked around the same issue by doing the following:

I changed line 94 from this:

```
print((str(iBlock) + ' blocks, ' + str((iBlock*FFUStoreHeader.dwBlockSizeInBytes)/1024) + 'kb written'), end="\r")
```

to this:

```
print((str(iBlock) + ' blocks, ' + str((iBlock*FFUStoreHeader.dwBlockSizeInBytes)/1024) + 'kb written') + '\r')
```

I also did this same for line 98. That's it! :)

**Comment by t0x0** [comment] 2016-01-12 18:08
Thanks for the input. Can you share your Python version, operating system, and which version of the FFU you converted? I was unable to reproduce the original report, so couldn't confirm a fix.
